name: praktikertjanst
description: Portal for praktikertjänst
version: 0.0.1
author: dmarl <dmarlovic83@gmail.com>
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angular: ^5.1.0
  angular_components: ^0.9.1
  angular_router: ^2.0.0-alpha+19
  d_components:
    git: https://github.com/afpatmin/d_components
  grid:
    git: https://github.com/afpatmin/grid
  fo_components:
    git: https://github.com/afpatmin/fo_components
  intl: ^0.15.7
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4+2
  sass_builder: ^2.1.1

dependency_overrides:
  build: ^1.0.1





