name: praktikertjanst
description: Portal for praktikertjänst
version: 0.0.1
author: dmarl <dmarlovic83@gmail.com>
environment:
  sdk: '>=2.1.0-dev.0.0 <3.0.0'
dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_router: ^2.0.0-alpha+19
  #animation:
    #git: https://github.com/afpatmin/Animation.git
  d_components:
    git: https://github.com/afpatmin/d_components.git
  grid:
    git: https://github.com/afpatmin/grid.git
  fo_components:
    git: https://github.com/afpatmin/fo_components.git
  intl: any
dev_dependencies:
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.2
  sass_builder: ^2.1.1




