name: praktikertjanst
description: Portal for praktikertjänst
version: 0.0.1
author: dmarl <dmarlovic83@gmail.com>
environment:
  sdk: ">=2.2.1-dev.3.0 <3.0.0"
dependencies:
  angular_router: ^2.0.0-alpha+21
  d_components:
    git: https://github.com/afpatmin/d_components
  grid_css: ^0.1.1
  intl: ^0.15.7
  http: ^0.11.3+16
  fo_components: 
    git: https://github.com/afpatmin/fo_components
  angular_components: ^0.12.0
  angular: ^5.3.0
dev_dependencies:
  sass_builder: ^2.1.1
  intl_translation: ^0.17.2
  build_runner: ^1.3.1
  build_web_compilers: ^1.2.0
